### ISSUE TITLE
Unable to add integration w/ station sensors 

### ISSUE THREAD

**Issue by johntdyer** [briis/weatherflow_forecast#210]
**Describe the bug**
When I try to add the station while checking the "include device sensors"  I get the following error

**To Reproduce**
1. Add integration
2. Check "include station sensors"
3. Apply

```




2024-12-30 16:41:14.441 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 388, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 491, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/weatherflow_forecast/config_flow.py", line 62, in async_step_user
    sensor_data: WeatherFlowSensorData = await weatherflow_api.async_fetch_sensor_data()
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyweatherflow_forecast/wffcst_lib.py", line 209, in async_fetch_sensor_data
    device_data: WeatherFlowDeviceData = _get_device_data(json_device_data, self._device_id)
                                         ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/pyweatherflow_forecast/wffcst_lib.py", line 577, in _get_device_data
    precipitation_type = None if api_result is None else api_result["obs"][0][13]
                                                         ~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
```

I am able to get past this by unchecking that option in the integration setup.  I then go back an check the now configured integration and I get the following error in the integration screen

```

2024-12-30 16:44:05.308 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Alpharetta' from integration weatherflow_forecast has an invalid unique_id '164431' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
2024-12-30 16:44:05.308 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Alpharetta' from integration weatherflow_forecast has an invalid unique_id '164431' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
2024-12-30 16:44:05.638 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.329 seconds (success: True)
2024-12-30 16:44:05.638 INFO (MainThread) [homeassistant.components.weather] Setting up weatherflow_forecast.weather
2024-12-30 16:44:05.640 INFO (MainThread) [homeassistant.helpers.entity_registry] Registered new weather.weatherflow_forecast entity: weather.forecast_alpharetta
2024-12-30 16:44:05.683 INFO (MainThread) [homeassistant.components.sensor] Setting up weatherflow_forecast.sensor
2024-12-30 16:44:05.683 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up weatherflow_forecast.binary_sensor
2024-12-30 16:44:17.848 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.676 seconds (success: False)
2024-12-30 16:44:23.422 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.293 seconds (success: False)
```

**Expected behavior**
this not to happen :) 

**Screenshots**

**Additional context**

**Comment by briis** [comment]
Would you mind posting your Station ID, or send it to me at bjarne@briis.com. Then I will have a look at the data that is returned.

**Comment by briis** [comment]
Never mind. I found the Station ID in the logs.
I just tried to setup the Station including the sensors, and all went well. I cannot reproduce the errors at this point in time. Perhaps you had a bad connection or the Station was not online when you tried to set it up?

Please try again, and let me know how this goes.
