### ISSUE TITLE
"Failed setup, will retry" with "Updated failed: 'time'"

### ISSUE THREAD

**Issue by eric** [briis/weatherflow_forecast#99]
**Describe the bug**

I recently have an error for my integration saying "Failed setup, will retry" with a mouse-over showing "Updated failed: 'time'".

In the logs it only says:

```
2024-03-25 18:00:14.008 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.332 seconds (success: False)
2024-03-25 18:00:54.756 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.319 seconds (success: False)
2024-03-25 18:02:15.173 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.353 seconds (success: False)
```

I have enabled debug logging and it doesn't appear to make a difference.

**To Reproduce**
1. Go to the installed WeatherFlow Forecast integration
2. See "Needs Attention" for the installed integration

**Comment by briis** [comment]
I cannot reproduce this right now. It can happen, when the Weatherflow Servers are not sending data, or you Internet temporary is down.

**Comment by eric** [comment]
Interesting. Would it be possible to improve the error message to make it more clear?

**Comment by briis** [comment]
Sure. I just need to capture the exact error that comes in from the API Request, so that I can raise the issue when it happens. I have already a few of them there, but obviously not them all.

**Comment by blindguynar** [comment]
Just saw this for the very first time tonight.  


![Screenshot 2024-04-16 at 9 43 16 PM](https://github.com/briis/weatherflow_forecast/assets/48634544/6cffc17d-987a-461a-8a70-996018e93d18)

**Comment by lazerdave** [comment]
Same issue today.  Started after a host system shutdown by my UPS.

**Comment by lazerdave** [comment]
Additional information:

It appears the API has either changed or is malfunctioning.

Getting raw data for all my stations by my token ID works at 
`https://swd.weatherflow.com/swd/rest/stations?token=[your_access_token]`

However, trying to access an individual station at
`https://swd.weatherflow.com/swd/rest/observations/station/[your_station_id]?token=[your_access_token]`
returns
```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<title>Payara Server 6.2023.2 #badassfish - Error report</title>
	<style type="text/css">
		<!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}
		-->
	</style>
</head>

<body>
	<h1>HTTP Status 404 - Not Found</h1>
	<hr />
	<p><b>type</b> Status report</p>
	<p><b>message</b>Not Found</p>
	<p><b>description</b>The requested resource is not available.</p>
	<hr />
	<h3>Payara Server 6.2023.2 #badassfish</h3>
</body>

</html>
```

**Comment by briis** [comment]
The above URL's both work fine for me with my Token and Station ID. Are you sure you have set your Station to Public Access? That is required for this to work.

**Comment by notmayo** [comment]
I'm getting this error right now and nothing has changed. Must be an API issue on Tempest's end even though my station is online and reachable via app and website.

**Comment by blindguynar** [comment]
> I'm getting this error right now and nothing has changed. Must be an API issue on Tempest's end even though my station is online and reachable via app and website.

same

**Comment by EvanMulawski** [comment]
Debug logging just shows:

```
2024-12-03 14:21:58.705 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.199 seconds (success: False)
2024-12-03 14:22:04.052 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.058 seconds (success: False)
2024-12-03 14:22:14.342 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.090 seconds (success: False)
2024-12-03 14:22:34.814 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.160 seconds (success: False)
2024-12-03 14:23:15.114 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.139 seconds (success: False)
2024-12-03 14:24:35.749 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.180 seconds (success: False)
2024-12-03 14:25:56.378 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.189 seconds (success: False)
2024-12-03 14:27:16.661 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.189 seconds (success: False)
2024-12-03 14:28:37.065 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.193 seconds (success: False)
```

Reloading the integration shows the "Update failed: time" error.

**Comment by Maarc** [comment]
> 2024-12-03 20:23:31.467 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.694 seconds (success: False)

It probably is an API issue. My ‘normal’ Weatherflow integration is working seamlessly. In the mean time, I changed everywhere possible the usage of the Weatherflow forecast sensors to the Weatherflow sensors.

**Comment by Maarc** [comment]
Little addendum: it seems to work again for me. No more errors.

**Comment by notmayo** [comment]
Confirmed my issue at least was a Tempest api issue.

**Comment by mwolter805** [comment]
Hello, started receiving this error `Failed setup, will retry: Update failed: 'time'` about four hours ago. Tempest app shows weatherstation online and there are no errors in the HA logs. 

Only entry in the debug logs is:
```
2025-01-11 14:27:33.566 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.465 seconds (success: False)
```

**Comment by notmayo** [comment]
> @briis Hello, started receiving this error `Failed setup, will retry: Update failed: 'time'` about four hours ago. Tempest app shows weatherstation online and there are no errors in the HA logs. 
> 
> 
> 
> Only entry in the debug logs is:
> 
> ```
> 
> 2025-01-11 14:27:33.566 DEBUG (MainThread) [custom_components.weatherflow_forecast] Finished fetching weatherflow_forecast data in 0.465 seconds (success: False)
> 
> ```

Heyo, chiming in to say that the integration is working fine for me and I even restarted HA and reloaded the integration to see if that breaks it.

The last time I had this issue Tempest was having an api issue. I'm wondering if maybe dns caching is giving you trouble since you're saying the app is working fine for you but the integration is not.

**Comment by mwolter805** [comment]
@notmayo Thanks for the reply. I've rebooted the HAOS host and both HAOS and the phone use the same DNS server, so I don't think it's a DNS caching issue but you never know!

**Comment by Ulrar** [comment]
Started getting this last night as well. The station is online, although it's in power saving mode, not sure if that's relevant

**Comment by mjnovotny82** [comment]
Mine started about 18 hours ago (~12 noon US Central time).  I'm still receiving current and past data with the Weatherflow local HA integrations, Android Tempest app, Tempestwx & Wunderground websites.

All API calls are showing `status":{"status_code":0,"status_message":"SUCCESS"}`.  I'm using the API calls referenced on [https://weatherflow.github.io/Tempest/api/](https://weatherflow.github.io/Tempest/api/)

**Comment by briis** [comment]
I have reopened the issue, but it is hard to debug with the information I can see above.
If the Station is in Power Save mode, it only reports a limited amount of data, so even though the API returns success, there can still be errors processing the data, as some data might not be in a state I expected.
For me to do more debugging, I need the Station ID's, as I have to look at the raw data being returned. If you don't want to post it here, send me an email on bjarne@briis.com

**Comment by mjnovotny82** [comment]
@briis I sent an email with my station ID

**Comment by Ulrar** [comment]
Sent one as well. Thanks!

**Comment by briis** [comment]
Thank you all. I have enough now to start debugging.

**Comment by aaronjudd** [comment]
Here are some more detailed logs from my install.  In addition to seeing 'Failed setup, will retry: Update failed:time'

```
2025-01-12 09:49:04.023 ERROR (MainThread) [homeassistant.config_entries] Config entry 'Pinyon  Trail' from integration weatherflow_forecast has an invalid unique_id '102256' of type int when a string is expected, please create a bug report at https://github.com/briis/weatherflow_forecast/issues
```

```
{"units_air_density":"kg/m3","units_brightness":"lux","units_distance":"km","units_other":"metric","units_precip":"mm","units_pressure":"mb","units_solar_radiation":"w/m2","units_temp":"c","units_wind":"mps"}} || to || <class 'weatherflow4py.models.rest.forecast.WeatherDataForecastREST'> -- 'pressure_trend'
2025-01-12 09:49:19.319 ERROR (MainThread) [homeassistant.components.weatherflow_cloud] Unexpected error fetching weatherflow_cloud data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/weatherflow_cloud/coordinator.py", line 35, in _async_update_data
    return await self.weather_api.get_all_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/weatherflow4py/api.py", line 175, in get_all_data
    weather=await self.async_get_forecast(station_id=station.station_id),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/weatherflow4py/api.py", line 106, in async_get_forecast
    return await self._make_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/weatherflow4py/api.py", line 68, in _make_request
    raise e
  File "/usr/local/lib/python3.13/site-packages/weatherflow4py/api.py", line 63, in _make_request
    return response_model.from_json(data) if response_model else None
           ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dataclasses_json/api.py", line 63, in from_json
    return cls.from_dict(kvs, infer_missing=infer_missing)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/dataclasses_json/api.py", line 70, in from_dict
    return _decode_dataclass(cls, kvs, infer_missing)
  File "/usr/local/lib/python3.13/site-packages/dataclasses_json/core.py", line 229, in _decode_dataclass
    value = _decode_dataclass(field_type, field_value,
                              infer_missing)
  File "/usr/local/lib/python3.13/site-packages/dataclasses_json/core.py", line 185, in _decode_dataclass
    field_value = kvs[field.name]
                  ~~~^^^^^^^^^^^^
KeyError: 'pressure_trend'
```

**Comment by davethetallguy** [comment]
I'm also seeing this error.  

Not mentioned by anyone else (that I noticed), when I look at the station using the Weatherflow web interface, I only have 4 days of forecast, stale current data, then a bunch of blank lines.  When I check on the iPhone app, it shows "offline, " and the same stale / missing data. 

Clicking in to the device details shows current data on both web and app. The discrepancy in app pages makes me suspicious of a server issue.

<img width="451" alt="Screenshot 2025-01-12 at 1 55 32 PM" src="https://github.com/user-attachments/assets/560c4a21-5125-4e73-98d8-ecf98e12a27d" />


<img width="903" alt="Screenshot 2025-01-12 at 2 05 32 PM" src="https://github.com/user-attachments/assets/3348f3f8-c1eb-4230-bda7-d2ee3ea63954" />

**Comment by mjnovotny82** [comment]
Seeing the same results with the forecast.  The rest API is also showing the same daily forecast issues, nothing daily is more than 4 days. https://swd.weatherflow.com/swd/rest/better_forecast?station_id=[your_station_id]&token=[your_access_token].

https://tempestwx.com/station/[your_station_id]/ is showing stale data but https://tempestwx.com/station/[your_station_id]/grid is showing my live data.

Looking at the HA code, are we grabbing / screen scraping data from https://tempestwx.com/station/{self._config.data[CONF_STATION_ID]}/grid or from the API site reference at https://weatherflow.github.io/Tempest/api/, https://weatherflow.github.io/Tempest/api/swagger/ ?

**Comment by briis** [comment]
> Looking at the HA code, are we grabbing / screen scraping data from [https://tempestwx.com/station/{self._config.data[CONF_STATION_ID]}/grid](https://tempestwx.com/station/%7Bself._config.data%5BCONF_STATION_ID%5D%7D/grid) or from the API site reference at https://weatherflow.github.io/Tempest/api/, https://weatherflow.github.io/Tempest/api/swagger/ ?

Data is pulled from the API. So if nothing gets send there, we will get nothing back. This seems to occur with some station in the Winter time, if they go in to Power Save mode.

**Comment by briis** [comment]
I think I found the main reason why it is failing. (Need a bit more testing). The observation @davethetallguy did with only 4 days of Forecast, turns out to be an issue with the Forecast data in general and it seems to only affect some stations. The Current Conditions data is simply missing some fields. If you look below, I have the data from one of the Stations you all send to me, that is failing, and below that, the data from my station. As you can see, several fields are not present. I handled most of them gracefully, but one missing field, made the integration crash.

I will work on a fix to not make the Integration fail, but I cannot do anything about the data, there you will have to contact WeatherFlow directly.

**Failing Station**
```json
 "current_conditions": {
        "air_temperature": -8.0,
        "conditions": "Partly Cloudy",
        "feels_like": -18.0,
        "icon": "partly-cloudy-night",
        "is_precip_local_day_rain_check": false,
        "relative_humidity": 73,
        "sea_level_pressure": 1009.2,
        "wind_avg": 10.0,
        "wind_direction": 279,
        "wind_direction_cardinal": "W",
        "wind_gust": 14.0
    },
````

**Working Station**
```json
"current_conditions": {
    "air_density": 1.33,
    "air_temperature": -4,
    "brightness": 582,
    "conditions": "Partly Cloudy",
    "delta_t": 0,
    "dew_point": -4,
    "feels_like": -4,
    "icon": "partly-cloudy-night",
    "is_precip_local_day_rain_check": false,
    "is_precip_local_yesterday_rain_check": true,
    "lightning_strike_count_last_1hr": 0,
    "lightning_strike_count_last_3hr": 0,
    "lightning_strike_last_distance": 24,
    "lightning_strike_last_distance_msg": "22 - 26 km",
    "lightning_strike_last_epoch": 1728479084,
    "precip_accum_local_day": 0,
    "precip_accum_local_yesterday": 0,
    "precip_minutes_local_day": 0,
    "precip_minutes_local_yesterday": 0,
    "precip_probability": 0,
    "pressure_trend": "steady",
    "relative_humidity": 96,
    "sea_level_pressure": 1038.7,
    "solar_radiation": 4,
    "station_pressure": 1031.9,
    "time": 1736753329,
    "uv": 0,
    "wet_bulb_globe_temperature": -4,
    "wet_bulb_temperature": -4,
    "wind_avg": 1,
    "wind_direction": 240,
    "wind_direction_cardinal": "WSW",
    "wind_gust": 2
  },
````

**Comment by briis** [comment]
So a Pre-Release named 1.0.13-beta-1 can now be downloaded from HACS.
Find the Integration in HACS, and select 'Download Again' and then select 'Need a different version' If you open the Drowdown, you should be able to see the Pre-Release.

Let me know if this fixes the issues for you.

**Comment by Ulrar** [comment]
1.0.13-beta-1 works for me, thanks !

**Comment by Ulrar** [comment]
Actually, I got this in the logs : 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/weatherflow_forecast/sensor.py", line 449, in async_setup_entry
    for description in SENSOR_TYPES if getattr(coordinator.data.sensor_data, description.key) is not None
                                       ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'absolute_humidity'
```

The integration still loaded and is providing data, but it logged this during startup

**Comment by briis** [comment]
I think this is a different issue. Here is the Raw data I get back when trying to pull data:

```json
{
  "status": {
    "status_code": 0,
    "status_message": "SUCCESS - Either no capabilities or no recent observations"
  },
  REST OF DATA REDACTED
```
I think your Hub might be Offline. Have checked that there is a green light at the back? If it is red, pull out the power and in again to restart. Once it is green, it should supply data.

**Comment by Ulrar** [comment]
Oh you're right, it just came offline an hour ago, hadn't noticed. I guess it's finally out of battery.

The integration loads anyway so it's not a huge deal, thanks for looking into it. I'll check again once it's back online, if we ever get any sun again

**Comment by briis** [comment]
> if we ever get any sun again

I know the feeling. I live in Denmark so I guess we get more or less the same amount of Daylight and Sunshine 😀
Last year i gave up and bought the Power Booster, since then, no issues with Battery running out.

**Comment by mjnovotny82** [comment]
1.0.13-beta-1 works for me, too. No errors appearing in the integration or logs.

**Comment by jdavidr17** [comment]
> 1.0.13-beta-1 works for me, too. No errors appearing in the integration or logs.

Same here.  Appreciation.

**Comment by jamesonp** [comment]
> So a Pre-Release named 1.0.13-beta-1 can now be downloaded from HACS. Find the Integration in HACS, and select 'Download Again' and then select 'Need a different version' If you open the Drowdown, you should be able to see the Pre-Release.
> 
> Let me know if this fixes the issues for you.

This resolves it for me.


Thank you!

**Comment by ki5ck** [comment]
I had the same issue, and the beta resolved it. Thank you for the quick work.

**Comment by davethetallguy** [comment]
Also to confirm: My forecast pages are still missing data (not your issue.)

The Integration no longer crashes.  Thanks for the assist!

**Comment by aaronjudd** [comment]
@briis Thanks for your efforts.  The beta fix works - in that it's not failing and is returning some data -  but not forecast (just restating this).  I also have seen the forecasting issue before.. There are a[ few posts in community](https://community.tempest.earth/t/weather-app-no-longer-showing-forecast/25358/15) but no acknowledgment from Tempest it seems.  I submitted a support ticket, as I am sure others have done.
However, my station is showing the full forecast and data set in the app, but not in the HA integration at the moment.

**Comment by briis** [comment]
@aaronjudd email me your station id and I will check if there are other issues with forecast, than the I did fix.  
I have seen it before that the App is showing data that cannot be pulled from the API.

**Comment by davethetallguy** [comment]
I'm showing full forecast now on the app, but as recently as 2 hours ago, I only had partial information.  Maybe let it cook for a couple of hours?

**Comment by mjnovotny82** [comment]
> I'm showing full forecast now on the app, but as recently as 2 hours ago, I only had partial information. Maybe let it cook for a couple of hours?

Same here.  All of a sudden, all forecast information. It was within the last couple of hours. You may need to do a reload on the integration by clicking on the 3 dots and selecting Reload.

![Screenshot_20250113_120109_Home Assistant](https://github.com/user-attachments/assets/c33b2273-2bb6-4a46-9f76-a3669d97755c)

**Comment by jayscovill** [comment]
Tempest support confirmed it was a bug and it should be resolved.  My forecast data in the webpage and app is complete now.

**Comment by aaronjudd** [comment]
Thanks all. Forecast and integration is working for me as well.

**Comment by briis** [comment]
Perfect. The main reason was obviously the bad data from the Forecast. But it also helped me to find that 1 line of code, that did not handle that gracefully.
